name: TF setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Azure-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: change directory
        run: |
          cd terraform

      - name: Terraform GitHub Actions
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          tf_actions_binary: 'terraform'
          tf_actions_subcommand: 'init'
          var_file: dev.tfvars
          backend_config: token={{ secrets.key }}
          backend_config_file: provider.tf