name: TF setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  terraform:
    name: Terraform
#    env:
#      ARM_CLIENT_ID: {{ secrets.CLIENT_ID }}
#      ARM_CLIENT_SECRET: {{ secrets.CLIENT_SECRET }}
#      ARM_SUBSCRIPTION_ID: {{ secrets.SUBSCRIPTION_ID }}
#      ARM_TENANT_ID: {{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Terraform Init
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          tf_actions_binary: 'terraform'
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './terraform'
          var_file: dev.tfvars

      - name: Terraform Validate
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './terraform'